# Generated by Django 2.2.3 on 2019-07-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('page_name', models.CharField(choices=[('Homepage', 'homepage'), ('About_us', 'about_us'), ('Contact', 'contact')], default='Homepage', max_length=100, unique=True)),
            ],
        ),
    ]
