# Generated by Django 2.2.3 on 2019-07-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_name',
            field=models.CharField(choices=[('Homepage', 'homepage'), ('About_us', 'about_us'), ('Contact', 'contact')], default='Homepage', max_length=100),
        ),
    ]
