# Generated by Django 2.2.3 on 2019-07-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_page_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_name',
            field=models.CharField(choices=[('Homepage', 'homepage'), ('About_us', 'about_us'), ('Contact', 'contact')], default='Homepage', max_length=100, unique=True),
        ),
    ]
