# Generated by Django 3.0.dev20190702105509 on 2019-07-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
